### ISSUE TITLE
login zone consideration

### ISSUE THREAD

**Issue by francy51** [wovencode/OpenMMO#42]
Login Zone is only ever displayed on screen now in Host/Play,  wondering if that's worthwhile or whether host/play should just start the character in their home zone to wander in...  I know the flow goes through LoginZone but it's bypassed in anything other than Host/Play as a graphic zone

**Comment by francy51** [comment]
If we see this as an issue we can add it as an official task to our todo list. Otherwise this issue will simply be closed.

**Comment by DX4D** [comment]
Login Zone display title changed to "Developer Test Room" - This room will be used during development to test features in Host and Play mode because zoning only works with a compiled server build. Because players will go directly to their home zone (Elf Realm etc) they will never have access to this room in a built client.
