### ISSUE TITLE
You should not ignore *.unitypackage

### ISSUE THREAD

**Issue by Fzcpp** [wovencode/OpenMMO#68]

**Comment by DX4D** [comment]
Do you have any reasoning behind this? We ignore them on purpose to keep optional packages out of the master build.

**Comment by Fzcpp** [comment]
version 0.13 have a "Core" directory, but missed in master branch, I guess you have put it in unitypackage, maybe not~

**Comment by DX4D** [comment]
The version from the Asset Store (0.13) is almost 5 months out of date in comparison to the git version at this point and there have been a number of significant refactors to the code structure since then. (The team no longer has a reliable method to update the Asset Store version)

I suggest getting the latest version from the Discord channel in the meantime and ignoring the Asset Store version until we are able to push the latest LTS version to the store.

**Comment by Joshua2504** [comment]
Isn't the project dead since a long time anyway?

**Comment by DX4D** [comment]
The project itself is not dead, but Fhiz is no longer involved, and I ended
up developing a number of tendonitis-related issues in my arm and
unfortunately cannot code anymore.

Therefore, with no developers, OpenMMO is now in LTS mode and won't be
getting new features added. It's not dead...it's finished 👍

**Comment by Joshua2504** [comment]
The current state of the project has nothing to do with LTS by far.

It's dead.

**Comment by DX4D** [comment]
Once my arm actually heals I'll be back to coding. If you lack the skill to use the version on the git to create a game then that's on you. We aren't working on this so ingrates can just hop on and asset flip it, move on if that's your expectation because you will only be disappointed here...this is a framework, not a template project.

**Comment by DX4D** [comment]
Any .unitypackage files included with openmmo will be compressed into a .zip file - This issue is no longer relevant.
