### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by Joshua2504** [wovencode/OpenMMO#70]
Do I take it right that you gave up on the project?

**Comment by DX4D** [comment]
I am the only one left that is contributing anymore, and my arm is shredded from coding too much. I'm out for quite a few months still at least.

Fhiz had mentioned coming back to this project at some point, but he got discouraged that nobody donates or contributed to the development and he dropped out fully from developing free software shortly after. His words (paraphrased): "If I can't make any money at all doing this, I might as well not make any money at all doing my own game instead" and then he deleted his account the next day. 

I'm not sure I really see myself sinking too much more time into this particular project either honestly. To put it bluntly, building someone else's mmo for free is a shit deal. :)

**Comment by DX4D** [comment]
I may continue to build upon this framework and create an actual mmo kit once I can get back to coding, but if I keep putting effort into this, I'm likely doing so as a paid product. Doing this as a free product simply has too many pitfalls to deal with. The fact is, if this were a paid product I could justify further investment into advertisement and paying a coder to add features while I am dealing with this injury. Instead, we just have to sit here and float while my arm heals and maybe we'll get lucky and someone will float on by and decide to lend a hand. Personally I am not a fan of being at the mercy of the tide, so that's my best idea on how to remedy the situation anyway.
